name: linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Env
      run: |
        sudo apt install openjdk-17-jre-headless
        sudo apt install spim
        mkdir -p $PWD/opt
        wget https://github.com/TheThirdOne/rars/releases/download/continuous/rars_27a7c1f.jar -O $PWD/opt/rars.jar
        cat > $PWD/opt/rars << EOF
        #!/bin/sh
        java -jar $PWD/opt/rars.jar "\$@"
        EOF
        chmod +x $PWD/opt/rars
        export PATH="$PATH:$PWD/opt"
    
    - name: Build
      run: make -j2

    - name: Test
      run: make test
