name: linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Env
      run: sudo apt install spim ninja-build llvm-15-dev gcc-11-riscv64-linux-gnu
    
    - name: Format
      run: make format-check

    - uses: actions/checkout@v3
      with:
        repository: dtcxzyw/qemu
        path: ${{github.workspace}}/qemu
    
    - name: Build qemu
      run: |
        cd qemu
        ./configure --target-list=riscv64-linux-user --enable-plugins
        make -j
        echo "QEMU_PATH=$(pwd)/" >> $GITHUB_ENV

    - name: Build
      run: |
        mkdir build && cd build
        cmake .. -G Ninja
        cmake --build . -j

    - name: Test
      run: cd build && ctest --verbose
